services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  mongodb:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
